[tool.poetry]
name = "human-slice-scripts"
version = "0.1.0"
description = "functions for analyzing ephys recordings"
authors = ["verjiniaM <87032309+verjiniaM@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
